image: maven:latest

stages: 
  - build
  - test
  - package
  - deploy
  
variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/
    - target/

build:
  stage: build
  script:
    - mvn compile

test: 
  stage: test 
  script: 
    - mvn verify 
  artifacts: 
  reports: 
  junit:
    - target/surefire-reports/TEST-*.xml
    - target/failsafe-reports/TEST-*.xml
  
package: 
  stage: package 
  script: 
    - mvn package 

deploy: 
  stage: deploy 
  script: 
    - mvn deploy -s ci_settings.xml

